version: '1.0'
services:
  - name: bp-db
    type: postgres
    version: 11.4
    configuration: StandAlone
    ports:
      - 5432
    username: botpress
    database: botpress
    userPassword: Letmein123
    remoteAccess: false
    deployTo:
      - botpress

  - name: bp
    type: docker
    image: botpress/server
    version: v12_8_1
    ports:
      - 3000
    remoteAccess: false
    env:
      MB_ENCRYPTION_SECRET_KEY: "{{=randomString(32)}}"
      PG_SSL: "false"
      BP_HOST: 0.0.0.0
      EXTERNAL_URL: "http://{{=service('bp').getBalancerDomain()}}"
      DATABASE_URL: "postgres://botpress:Letmein123@bp-db-master:5432/botpress"
      BPFS_STORAGE: "database"
      BP_PRODUCTION: true
    volumes:
      - directory: /botpress/data
    deployTo:
      - botpress

  - name: bp-web
    type: nginx
    version: 1.17
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: botpress
    deployTo:
      - botpress

hosts:
  - name: botpress
    requirements:
      cores: 1
      memory: 2
